# Generated by Django 4.1.7 on 2023-06-05 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='post',
        ),
        migrations.AlterModelTable(
            name='tag',
            table='tag',
        ),
    ]
