# Generated by Django 4.1.7 on 2023-06-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_alter_post_table_alter_tag_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tag',
            name='weight',
            field=models.IntegerField(max_length=100),
        ),
    ]
