# Generated by Django 4.1.7 on 2023-06-06 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_alter_tag_name_alter_tag_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='weight',
            field=models.IntegerField(),
        ),
    ]
